---
- name: Weberser installation
  hosts: 10.211.55.36
  become: yes
  tasks:
    - name: install httpd
      dnf: name=httpd
    - name: enable and start httpd
      systemd: 
        name: httpd 
        enabled: true 
        state: started
    - name: creating the index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "WELCOME TO DCM LINUX"
        create: yes
    - name: open firewall port
      firewalld:
        service: http
        state: enabled
        immediate: yes

