---
- name: Weberser installation
  hosts: 10.211.55.32
  become: yes
  tasks:
    - name: install httpd
      dnf: name=httpd
    - name: enable and start httpd
      systemd: 
        name: httpd 
        enabled: true 
        state: started
    - name: creating the index.html
      copy:
        content: "WELCOME TO DCM LINUX"
        dest: /var/www/html/index.html
        node: 0444
    - name: open firewall port
      firewalld:
        service: httpd
        permanent: true
        state: enabled
        immediate: yes

